### PR TITLE
spell check added.

### PR DESCRIPTION
**Pull request by sujith-mn**

### CODE REVIEW

**Comment by ohecker** [comment]
Hi @sujith-mn : Is there any additional info on introducing spellcheck in the devonfw repos? (any general ticket or resource?). I see that there are a lot of CamelCase named things in the user guide being marked as spelling errors. How can we adopt rules here?

**Comment by sujith-mn** [comment]
> Hi @sujith-mn : Is there any additional info on introducing spellcheck in the devonfw repos? (any general ticket or resource?). 
Yes.. There is a ticket created on Devonfw JIRA for introducing spell check for all devonfw repos. 
>I see that there are a lot of CamelCase named things in the user guide being marked as spelling errors. How can we adopt rules here?
Could not find any rules to handle the Camelcase words. All such words can be added to the custom dictionary. Some of it has already added.

**Comment by ohecker** [comment]
Just relying on a centrally curated dictionary is IMHO to inflexible. I would even not prefer to add the (very Solicitor specific) CamelCase words to any central dictionary. I added a project specific dictionary in https://github.com/ohecker/solicitor-1/tree/spellcheck which fixes the remaining found issues.  If this is OK for you then please merge this into your branch master@sujith-mn/solicitor and I will then merge the PR.

**Comment by sujith-mn** [comment]
One benefit of central dictionary I could see is, the words in the dictionary are often common for other repositories. So define it only once in a single place is good.

**Pull request merged**
